sources:
  - type: golang
    path: go.mod
version: 0.2.12
excludes:
  # Need to generate Swagger API Description before running PK
  - "E-PK-CORE-18: Outdated content: '.github/workflows/project-keeper-verify.yml'"
