basePath: /api/v1
info:
  contact:
    name: Exasol REST API GitHub Issues
    url: https://github.com/exasol/exasol-rest-api/issues
  description: This service is a proxy that wrapping up Exasol WebSockets library.
  license:
    name: MIT License
    url: https://github.com/exasol/exasol-rest-api/blob/main/LICENSE
  title: Exasol REST API
  version: 0.1.0
paths:
  /query/{query}:
    get:
      consumes:
      - application/json
      description: provide a query and get a result set
      parameters:
      - description: SELECT query
        in: path
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Query the Exasol databse.
swagger: "2.0"
