name: Go Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  matrix-build:
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - go: "1.24.9"
            db: "7.1.30"
          - go: "1.25.3"
            db: "8.29.12"
          - go: "1.25.3"
            db: "2025.1.3"
    env:
      DEFAULT_GO: "1.25.3"
      DEFAULT_DB: "2025.1.3"
    name: Build with Go ${{ matrix.go }} and Exasol ${{ matrix.db }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache OpenFastTrace
        uses: actions/cache@v4
        with:
          path: |
            /tmp/oft/
          key: oft-${{ hashFiles('trace-requirements.sh') }}
          restore-keys: |
            oft-

      - name: Trace requirements
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB
        run: ./trace-requirements.sh

      - name: Build Docker Image
        run: docker buildx build --tag rest-api-test-image:latest .

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@v1.16.6

      - name: Generate Swagger API Description
        run: ./generate-swagger-docs

      - name: Run short tests
        run: go test -v -short ./...

      - name: Run all tests with Exasol ${{ matrix.db }}
        run: go test -v -p 1 -count 1 -coverprofile=coverage.out ./... -timeout 2000s
        env:
          EXASOL_DB_VERSION: ${{ matrix.db }}
          
      - name: SonarCloud Scan
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB && github.repository_owner == 'exasol'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: golangci-lint
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.6.0
          skip-cache: true

      - name: Run Go vulnerability check
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -version
          govulncheck -format text -mode source -scan symbol -show verbose -test ./...

      - name: Configure broken links checker
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB
        run: |
          mkdir -p ./target
          echo '{"aliveStatusCodes": [429, 200], "ignorePatterns": [' \
               ']}' > ./target/broken_links_checker.json
      - uses: tcort/github-action-markdown-link-check@v1
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ./target/broken_links_checker.json
  
  build:
    needs: matrix-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo "Build successful"
