name: Go Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go: [ "1.20" ]
        db: [ "8.24.0" ]
    env:
      DEFAULT_GO: "1.20"
      DEFAULT_DB: "8.24.0"
    name: Build with Go ${{ matrix.go }} and Exasol ${{ matrix.db }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Cache OpenFastTrace
        uses: actions/cache@v3
        with:
          path: |
            /tmp/oft/
          key: oft-${{ hashFiles('trace-requirements.sh') }}
          restore-keys: |
            oft-

      - name: Trace requirements
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB
        run: ./trace-requirements.sh

      - name: Build Docker Image
        run: docker build --tag rest-api-test-image:latest .

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@v1.16.2

      - name: Generate Swagger API Description
        run: ./generate-swagger-docs

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-go-installation: true
          skip-pkg-cache: true

      - name: Run all tests with Exasol ${{ matrix.db }}
        run: go test -v -p 1 -coverprofile=coverage.out ./... -timeout 2000s
        env:
          DB_VERSION: ${{ matrix.db }}

      - name: SonarCloud Scan
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB && github.repository_owner == 'exasol'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
