name: Dependencies Check

on:
  schedule:
    - cron: "0 23 * * *"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Nancy Security scanner
        run: go list -json -deps | docker run --rm -i sonatypecommunity/nancy:latest sleuth --skip-update-check
        env:
          OSSI_USERNAME: ${{ secrets.OSSINDEX_USERNAME }}
          OSSI_TOKEN: ${{ secrets.OSSINDEX_API_TOKEN }}
