name: Go Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build with Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: docker build --tag rest-api-test-image:latest .

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@v1.7.3
      - name: Generate Swagger API Description
        run: ./generate-swagger-docs

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          skip-go-installation: true
          skip-pkg-cache: true

      - name: test
        run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        if: github.repository_owner == 'exasol'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}