name: Go Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build with Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Swag
        run: go get -u github.com/swaggo/swag/cmd/swag
      - name: Setup Enviroment variable for Swagger
        run: export PATH=$(go env GOPATH)/bin:$PATH
      - name: Generate Swagger API Description
        run: bash generate-swagger-docs

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5
        with:
          version: v1.42

      - name: test
        run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        if: github.repository_owner == 'exasol'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}