name: Go Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go: [ "1.17" ]
        db: [ "7.0.16", "7.1.6" ]
    env:
      DEFAULT_GO: "1.17"
      DEFAULT_DB: "7.1.6"
    name: Build with Go ${{ matrix.go }} and Exasol ${{ matrix.db }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Cache OpenFastTrace
        uses: actions/cache@v2
        with:
          path: |
            /tmp/oft/
          key: oft-${{ hashFiles('trace-requirements.sh') }}
          restore-keys: |
            oft-

      - name: Trace requirements
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB
        run: ./trace-requirements.sh

      - name: Build Docker Image
        run: docker build --tag rest-api-test-image:latest .

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@v1.8.0

      - name: Generate Swagger API Description
        run: ./generate-swagger-docs

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
          skip-pkg-cache: true

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
        env:
          GO111MODULE: on

      - name: Nancy Security scanner
        run: go list -json -deps | docker run --rm -i sonatypecommunity/nancy:latest sleuth

      - name: test
        run: go test -v -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        if: matrix.go == env.DEFAULT_GO && matrix.db == env.DEFAULT_DB && github.repository_owner == 'exasol'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}