name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Assets upload URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@v1.8.12
      - name: Setup Environment variable for Swagger
        run: export PATH=$(go env GOPATH)/bin:$PATH
      - name: Generate Swagger API Description
        run: bash generate-swagger-docs

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/exasol-rest-api
      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o build/exasol-rest-api-x86-64.exe
      - name: Generate sha256sum files
        run: find build -name exasol-rest-api* -exec bash -c 'sha256sum {} > {}.sha256' \;

      - name: Upload assets and sha256sum files to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: build/*
